### PR TITLE
Update UG Screenshots

### LINKED ISSUE #231: Make Quick start more useful
Annotation of Ui image 
- Student panel
- Command box
- Module panel

Link to FAQ to Mac issues

### LINKED ISSUE #236: Change Before and After to Annotation of After Images
mod mark command and select batchmate command

### PR DESCRIPTION
**Pull request by jonasgwt**
Fixes #231 
Fixes #236

### CODE REVIEW

**Review by sltsheryl — APPROVED** [review]
The labels look good 👍 
LGTM

**Comment by sltsheryl** [comment]
Hmm it's not showing on the UG @jonasgwt

**Comment by jonasgwt** [comment]
> Hmm it's not showing on the UG @jonasgwt

can try open in incognito I think it takes a while

**Comment by sltsheryl** [comment]
> > Hmm it's not showing on the UG @jonasgwt
> 
> can try open in incognito I think it takes a while

Yup it shows 👍

**Pull request merged**
